INSERT INTO picture(name) VALUES ('Бурлаки идущие вброд');
INSERT INTO picture(name) VALUES ('Явление Христа народу');
INSERT INTO picture(name) VALUES ('Эрминия у пастухов');
INSERT INTO picture(name) VALUES ('Фрукты');
INSERT INTO picture(name) VALUES ('Натюрморт');
INSERT INTO picture(name) VALUES ('Неравный брак');
INSERT INTO picture(name) VALUES ('Охотники на привале');
INSERT INTO picture(name) VALUES ('Демон сидящий');
INSERT INTO picture(name) VALUES ('Не ждали');
INSERT INTO picture(name) VALUES ('Девочка с персиками');
INSERT INTO picture(name) VALUES ('Гитарист');
INSERT INTO picture(name) VALUES ('Всадница');
INSERT INTO picture(name) VALUES ('Всюду жизнь');
INSERT INTO picture(name) VALUES ('Утро в сосновом лесу');
INSERT INTO picture(name) VALUES ('Пантелеймон-целитель');
INSERT INTO picture(name) VALUES ('Царевна-лебедь');
INSERT INTO picture(name) VALUES ('Отдых');
INSERT INTO picture(name) VALUES ('Портрет Л. Н. Толстого');
INSERT INTO picture(name) VALUES ('Великий князь Павел Александрович');
INSERT INTO picture(name) VALUES ('Приам испрашивающий у ахиллеса тело Гектора');
INSERT INTO picture(name) VALUES ('Вид Леандровой башни в Константинополе');
INSERT INTO picture(name) VALUES ('Всадник-воин в Джайпуре');
INSERT INTO picture(name) VALUES ('Запорожцы пишут письмо турецкому султану');